name: Build


on:
  pull_request:

jobs:
    dependencies:
        name: Build dependencies
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version.outputs.version }}

        steps:
            - name: Check out source files
              uses: actions/checkout@v3

            - name: Create global variables
              id: version
              run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    determine-matrix:
      name: Figure out the packages we need to build
      runs-on: ubuntu-latest

      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}

      steps:
        - name: Set up Git repository
          uses: actions/checkout@v3

        - name: Install Nix
          uses: DeterminateSystems/nix-installer-action@main

        - id: set-matrix
          run: |
            echo "matrix=$(
              nix eval --json --impure --expr 'builtins.attrNames (import ./.).packages.x86_64-linux'
            )" >> $GITHUB_OUTPUT

    build-typst-dev:
      name: Build and cache typst binary
      runs-on: ubuntu-latest

      steps:
        - name: Set up Git repository
          uses: actions/checkout@v3

        - name: Install Nix
          uses: DeterminateSystems/nix-installer-action@main

        - name: Run the Magic Nix Cache
          uses: DeterminateSystems/magic-nix-cache-action@main

        - name: Build typst
          run: |
            nix build .#typst

    build:
        name: Build PDF document
        runs-on: ubuntu-latest
        needs: [dependencies, determine-matrix, build-typst-dev]
        strategy:
          fail-fast: false
          matrix:
            packages: ${{fromJson(needs.determine-matrix.outputs.matrix)}}

        steps:
            - name: Set git to use LF
              run: |
                git config --global core.autocrlf false
                git config --global core.eol lf

            - name: Check out source files
              uses: actions/checkout@v3

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Run the Magic Nix Cache
              uses: DeterminateSystems/magic-nix-cache-action@main

            - name: Build ${{ matrix.packages }}
              run: |
                nix build .#${{ matrix.packages }}
                cp result/${{ matrix.packages }}.pdf ${{ matrix.packages }}.pdf

            - name: Upload build assets
              uses: actions/upload-artifact@v3
              with:
                name: assets
                path: "*.pdf"
