name: Build


on:
  push:
    branches:
      - main

jobs:
    dependencies:
        name: Build dependencies
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version.outputs.version }}

        steps:
            - name: Check out source files
              uses: actions/checkout@v3

            - name: Create global variables
              id: version
              run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    determine-matrix:
      name: Figure out the packages we need to build
      runs-on: ubuntu-latest

      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}

      steps:
        - name: Set up Git repository
          uses: actions/checkout@v3

        - name: Install the Nix package manager
          uses: cachix/install-nix-action@v20

        - id: set-matrix
          run: |
            echo "matrix=$(
              nix eval --json --impure --expr 'builtins.attrNames (import ./.).packages.x86_64-linux'
            )" >> $GITHUB_OUTPUT

    build-typst-dev:
      name: Build and cache typst binary
      runs-on: ubuntu-latest

      steps:
        - name: Install Nix
          uses: cachix/install-nix-action@v20

        - uses: cachix/cachix-action@v12
          with:
            name: typst-document
            authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

        - name: Build typst bleeding edge
          run: |
            nix build github:typst/typst

    build:
        name: Build PDF document
        runs-on: ubuntu-latest
        needs: [dependencies, determine-matrix, build-cache-typst]
        strategy:
          fail-fast: true
          matrix:
            packages: ${{fromJson(needs.determine-matrix.outputs.matrix)}}

        steps:
            - name: Set git to use LF
              run: |
                git config --global core.autocrlf false
                git config --global core.eol lf

            - name: Check out source files
              uses: actions/checkout@v3

            - name: Install Nix
              uses: cachix/install-nix-action@v20

            - uses: cachix/cachix-action@v12
              with:
                name: typst-document
                authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Build ${{ matrix.packages }}
              run: |
                nix build .#${{ matrix.packages }}
                cp result/${{ matrix.packages }}.pdf ${{ matrix.packages }}.pdf

            - name: Upload build assets
              uses: actions/upload-artifact@v3
              with:
                name: assets
                path: "*.pdf"

    release:
        name: "Create tag/pre-release"
        runs-on: ubuntu-latest
        needs: [dependencies, build]
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
            - name: Create pre-release (${{ needs.dependencies.outputs.version }})
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: v${{ github.run_number }}-${{ needs.dependencies.outputs.version }}
                release_name: Version ${{ github.run_number }} (${{ needs.dependencies.outputs.version }})
                draft: false
                prerelease: true

    assets:
        name: Upload release assets
        runs-on: ubuntu-latest
        needs: [dependencies, determine-matrix, release]
        strategy:
          fail-fast: false
          matrix:
            packages: ${{fromJson(needs.determine-matrix.outputs.matrix)}}

        steps:
            - name: Download build assets (${{ matrix.assets.input }})
              uses: actions/download-artifact@v3
              with:
                name: assets
                path: assets

            - name: Upload release assets
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ needs.release.outputs.upload_url }}
                asset_path: assets/${{ matrix.packages }}.pdf
                asset_name: ${{ github.run_number }}--${{ matrix.packages }}--${{ needs.dependencies.outputs.version }}.pdf
                asset_content_type: application/pdf
