name: 'Update flake lock file'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-flake:
    uses: loophp/flake-lock-update-workflow/.github/workflows/upgrade-flakes.yaml@main