name: 'Update flake lock file'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 3am UTC

jobs:
  update-flake:
    uses: loophp/flake-lock-update-workflow/.github/workflows/upgrade-flakes.yaml@main